# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '11.0'

target 'DragDropUpDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

   pod 'YYModel'
   pod 'LookinServer', :configurations => ['Debug']

end
