use_frameworks!
platform :ios, '12.0'
target 'BMLongPressDragCellCollectionView_Example' do
  pod 'BMLongPressDragCellCollectionView', :path => '../'
  
  pod 'WMPageController', '2.3.0'
  pod 'BlocksKit', '2.2.5'
  pod 'SVProgressHUD', '2.2.2'
  pod 'Masonry'
  pod 'UICollectionViewDynamicLayoutCacheSize'
  pod 'AMLeaksFinder'
  pod 'SnapKit'
  pod 'LookinServer', :configurations => ['Debug']

end
