# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'RCDragDropAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCDragDropAnimation
  pod 'Kingfisher', '~> 7.6.0'
  pod 'LookinServer', :configurations => ['Debug']

  
  target 'RCDragDropAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RCDragDropAnimationUITests' do
    # Pods for testing
  end

end
